export const data = [
    {
        city_mpg: 23,
        class: "ferrari",
        combination_mpg: 45,
        cylinders: 64,
        displacement: 32,
        drive: "awd",
        fuel_type: "gas",
        highway_mpg: 42,
        make: "Toyota",
        model: "Land Cruiser Prado",
        transmission: "a",
        year: 1994
    },
    {
        city_mpg: 32,
        class: "wagon",
        combination_mpg: 45,
        cylinders: 64,
        displacement: 32,
        drive: "4wd",
        fuel_type: "diesel",
        highway_mpg: 42,
        make: "Toyota",
        model: "corolla",
        transmission: "m",
        year: 1994
    },
    {
        city_mpg: 18,
        class: "wagon",
        combination_mpg: 45,
        cylinders: 64,
        displacement: 32,
        drive: "rwd",
        fuel_type: "gas",
        highway_mpg: 42,
        make: "Toyota",
        model: "camry",
        transmission: "a",
        year: 1994
    },
    {
        city_mpg: 51,
        class: "wagon",
        combination_mpg: 45,
        cylinders: 64,
        displacement: 32,
        drive: "2wd",
        fuel_type: "diesel",
        highway_mpg: 42,
        make: "Toyota",
        model: "Axio",
        transmission: "a",
        year: 1994
    },
    {
        city_mpg: 43,
        class: "wagon",
        combination_mpg: 45,
        cylinders: 64,
        displacement: 32,
        drive: "awd",
        fuel_type: "gas",
        highway_mpg: 42,
        make: "Toyota",
        model: "Rav4",
        transmission: "a",
        year: 1994
    },
]